# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x25641c2e1c0
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.52213591 0.23156101 0.11748991]
 [0.32146283 0.49185407 0.09686116]
 [0.38474424 0.59642274 0.28747448]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [ ]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

In [10]:
arr.__sizeof__()

184

### ЗАВДАННЯ 1

In [11]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.array([[1.5, 2, 3, 4.8], [5, 6.9, 7.2, 8], [9, 10.9, 11, 12.5]])
np.info(arr1_1[0])

class:  ndarray
shape:  (4,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x25620549e80
byteorder:  little
byteswap:  False
type: float64


In [12]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = ['Маріуполь','Чорнобаївка','Одеса','Київ','Львів']
print(arr1_2)

['Маріуполь', 'Чорнобаївка', 'Одеса', 'Київ', 'Львів']


In [14]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.random.uniform(5.5,9.5,size=(3,4))
print(arr1_3)

[[9.20985883 7.32594971 8.64567535 7.83924632]
 [7.7636346  7.57715937 9.47034786 7.75610772]
 [5.65309749 5.52937299 6.16779512 5.96408522]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [15]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [16]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [17]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [18]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [19]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.full((3,1,3),False)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [20]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape(3,3)
print(arr2_2)
arr2_2 = arr2_2.astype('int64')
print(arr2_2)

[[False False False]
 [False False False]
 [False False False]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2).reshape(2,3)
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [22]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [23]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[36 20 15 22]
 [28 36 19 38]
 [16 12 30 48]
 [39 34 30 24]]


In [24]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, 2]
print(el)

19


In [25]:
# отримати значення останнього рядка
vect = arr[2]
print(vect)

[16 12 30 48]


In [26]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[36 20 15 22]
 [28 36 19 38]]


In [27]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[20 15]
 [36 19]
 [12 30]
 [34 30]]


In [28]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[36 20 15 22]
 [16 12 30 48]]


In [29]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[36 22 28 36 38 30 48 39 34 30 24]


### ЗАВДАННЯ 3

In [30]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10,100,size=(4,5))
print(arr3_1)

[[87 48 25 12 57]
 [31 19 67 37 96]
 [64 30 33 19 66]
 [82 38 38 41 26]]


In [31]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1][2]
print(el3_2)

67


In [32]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[31 19 67 37 96]


In [33]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[:, 2]
print(vect3_4)

[25 67 33 38]


In [34]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[19 67]
 [30 33]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [35]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [37]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.07358989 0.09181062 0.65016405 0.35910196 0.92954369]
 [0.2403252  0.49034769 0.42746563 0.6759663  0.54583346]
 [0.88812627 0.30666517 0.87815485 0.83396289 0.59488754]
 [0.66641493 0.89336955 0.88886893 0.90540565 0.93640621]
 [0.23101864 0.56744735 0.68414747 0.65382942 0.47843656]]
...
[0.07358989 0.49034769 0.87815485 0.90540565 0.47843656]


In [38]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.07358989 0.2403252  0.88812627 0.66641493 0.23101864]
 [0.09181062 0.49034769 0.30666517 0.89336955 0.56744735]
 [0.65016405 0.42746563 0.87815485 0.88886893 0.68414747]
 [0.35910196 0.6759663  0.83396289 0.90540565 0.65382942]
 [0.92954369 0.54583346 0.59488754 0.93640621 0.47843656]]


In [39]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.039270467721173756


In [40]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[-0.50525524 -0.77652949  0.81205037  1.4207726  -1.92290139]
 [-0.75088062 -1.17423905 -1.22005454  1.97913225  0.44193699]
 [ 0.44401298 -3.02762301  0.33709978 -0.49608697  3.14326089]
 [-0.38741642  3.87844407  0.7675982  -2.41056555  0.09148526]
 [ 1.02906535  0.79678569 -0.47610554  0.97027915 -2.12529674]]


### ЗАВАДАННЯ 4

In [41]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100,200,size=(6,6))
print(mat4_1)

[[114 110 196 149 193 128]
 [159 165 165 167 175 159]
 [110 141 138 107 172 191]
 [197 147 136 157 107 162]
 [105 175 164 116 190 107]
 [104 162 132 100 165 141]]


In [42]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[114 165 138 157 190 141]


In [43]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[114 159 110 197 105 104]
 [110 165 141 147 175 162]
 [196 165 138 136 164 132]
 [149 167 107 157 116 100]
 [193 175 172 107 190 165]
 [128 159 191 162 107 141]]


In [44]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[-0.72803795  0.15694527  1.43942653  0.08988224  1.77140927 -2.91345832]
 [ 0.38333507 -0.09193613 -0.77767399 -0.04050523 -0.94131686  1.56999602]
 [ 0.56273877 -0.16835532 -1.0796871  -0.03986433 -1.31333437  2.1839927 ]
 [ 0.35633114 -0.04095069 -0.72193644 -0.05612256 -0.89018807  1.44065682]
 [-0.790052    0.20192998  1.55627694  0.07039519  1.90395712 -3.14437261]
 [ 0.24155755 -0.05978107 -0.46659948 -0.02501252 -0.59224974  0.96545441]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [45]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [46]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [47]:
# матриця 3х4 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [48]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [49]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [50]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [51]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [52]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [53]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


<ipython-input-53-df0164db1db1>:2: RuntimeWarning: divide by zero encountered in true_divide
  K = N / M


In [54]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [55]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [56]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [57]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [58]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [59]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[5 2 6 1 4]
[5 2 6 1 4]
2569514701248 2569514701248
[5 2 6 1 4]
2569514701248 2569514650720


In [60]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [61]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(0,100,size=(3,4))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[13 35 73 78]
 [23  4 52 69]
 [77  3 30 17]]
[199 148 127]


In [62]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

3


In [63]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1+100
print(mat5_3)

[[113 135 173 178]
 [123 104 152 169]
 [177 103 130 117]]


In [64]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
diag5_4 = np.diag(mat5_3)
mat5_4 = np.dot(diag5_4, mat5_1 )
print(mat5_4)

[13871  4761 17557 18200]


In [65]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.array([mat5_3[0],mat5_3[1],mat5_3[2],mat5_4])
print(mat5_5)
np.linalg.matrix_rank(mat5_5)

[[  113   135   173   178]
 [  123   104   152   169]
 [  177   103   130   117]
 [13871  4761 17557 18200]]


4